apiVersion: apps/v1
kind: Deployment

metadata:
  name: echo-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app

  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: echo-container
          image: echo-server:3.0
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            # spring에서 대문자 -> 소문자, _ -> . 로 매핑
            - name: GREETING_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: echo-config
                  key: GREETING_MESSAGE
            - name: GREETING_SECRET
              valueFrom:
                secretKeyRef:
                  name: echo-secret
                  key: GREETING_SECRET
      restartPolicy: Always
